name: CI
on: [push, pull_request]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: master
      - uses: nektro/actions-setup-zigmod@v1
      - run: zigmod fetch
      - run: zig build test
