name: CI

on:
  push:
    branches:
      - master
      - release/*
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: master
      - run: zig build test
