name: CI
on: [push, pull_request]
jobs:
  ci:
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup Linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install libgtk-3-dev
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: master
      - uses: nektro/actions-setup-zigmod@v1
      - run: zigmod fetch
      - name: Build Capy
        run: zig build
